<a href="https://colab.research.google.com/github/danielbr20998/Atividade-6-7/blob/main/Atividade_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [366]:
# ATV 8 = Analise de peças de produção:
# Uma fábrica de peças mecânicas registrou sua produção de unidades
# Ao longo de 4 semanas para 3 linhas de produção.
# Cada linha fabrica um tipo diferente de peça
# (A, B e C). Os dados foram organizados da seguinte forma:
# Linhas (0 a 3): semanas 1 a 4
# Colunas (0 a 2): peças A, B e C

import statistics as st
import numpy as np
import random as ran

In [367]:
print(' A, B, C')
semanas = np.random.randint(1, 10, size= (4, 3))
print(semanas)

 A, B, C
[[6 4 5]
 [9 6 1]
 [3 6 5]
 [4 5 9]]


In [368]:
# Total de peças produzidas por semana:
# Calcule a soma total de peças produzidas em cada semana.
# Produção total de cada tipo de peça:
# Calcule o total produzido das peças A, B e C ao longo das 4 semanas.
# Semana com maior produção total:
# Identifique qual semana teve a maior produção somando todos os tipos de peças.
# Média semanal de produção por tipo de peça:
# Calcule a média semanal de produção para cada tipo de peça.

In [369]:
producao1 = semanas[0]
producao2 = semanas[1]
producao3 = semanas[2]
producao4 = semanas[3]
produto1 = semanas[:, 0]
produto2 = semanas[:, 1]
produto3 = semanas[:, 2]

print('Produção semana 1: ', producao1)
print('Produção semana 2: ', producao2)
print('Produção semana 3: ', producao3)
print('Produção semana 4: ', producao4)
print('Produção peça A: ', produto1)
print('Produção peça B: ', produto2)
print('Produção peça C: ', produto3)

Produção semana 1:  [6 4 5]
Produção semana 2:  [9 6 1]
Produção semana 3:  [3 6 5]
Produção semana 4:  [4 5 9]
Produção peça A:  [6 9 3 4]
Produção peça B:  [4 6 6 5]
Produção peça C:  [5 1 5 9]


In [370]:
total_prod1 = sum(produto1)
total_prod2 = sum(produto2)
total_prod3 = sum(produto3)
print('Total produção produto A: ', total_prod1)
print('Total produção produto B: ', total_prod2)
print('Total produção produto C: ', total_prod3)

total_geral = total_prod1 + total_prod2 + total_prod3
print('Total geral:', total_geral)

totais = [total_prod1, total_prod2, total_prod3]
letras = ['A', 'B', 'C']

indice_maior = totais.index(max(totais))
print('Produto com maior produção é', letras[indice_maior], 'com', totais[indice_maior], 'peças totais')

Total produção produto A:  22
Total produção produto B:  21
Total produção produto C:  20
Total geral: 63
Produto com maior produção é A com 22 peças totais


In [371]:
total_sem1 = sum(producao1)
total_sem2 = sum(producao2)
total_sem3 = sum(producao3)
total_sem4 = sum(producao4)

print('Total produção semana 1: ', total_sem1)
print('Total produção semana 2: ', total_sem2)
print('Total produção semana 3: ', total_sem3)
print('Total produção semana 4: ', total_sem4)

maior_sem = max(total_sem1, total_sem2, total_sem3, total_sem4)
print('\n Semana com maior produção:', maior_sem)

Total produção semana 1:  15
Total produção semana 2:  16
Total produção semana 3:  14
Total produção semana 4:  18

 Semana com maior produção: 18


In [372]:
media_prod1 = st.mean(produto1)
media_prod2 = st.mean(produto2)
media_prod3 = st.mean(produto3)

print('Média semanal produção produto A: ', media_prod1)
print('Média semanal produção produto B: ', media_prod2)
print('Média semanal produção produto C: ', media_prod3)

Média semanal produção produto A:  5
Média semanal produção produto B:  5
Média semanal produção produto C:  5


In [373]:
# Peça com maior média de produção:
# Indique qual peça (A, B ou C) teve a maior média de produção nas 4 semanas.
# Crescimento semanal da produção da peça A:
# Calcule a variação percentual semanal da produção da peça A.
# Peças abaixo da média:
# Liste as semanas em que alguma peça foi produzida em quantidade abaixo da média do seu tipo.

In [374]:
max_media = [media_prod1, media_prod2, media_prod3]
media_maior = max_media.index(max(max_media))
print('Peça com maior média de produção é', letras[media_maior], 'com', max_media[media_maior], 'peças')


Peça com maior média de produção é A com 5 peças


In [375]:
# Variação percentual do produto A:

print(produto1)

valor_in = 3
valor_fin = 5

VP = ((valor_fin - valor_in) / valor_in) * 100
print(f"Variação percentual: {VP:.2f}%")

[6 9 3 4]
Variação percentual: 66.67%


In [376]:
abaixo_media = [num for num in produto1 if num < media_prod1]

print("Média:", media_prod1)
print("Números abaixo da média:", abaixo_media)

Média: 5
Números abaixo da média: [np.int64(3), np.int64(4)]
